// Hardcoded per-state legal reference data. Sourced from each state bar
// association's published website and the state judiciary's public pages.
// Verified 2026-04-12. Update at least every 12 months.

export interface StateLegalData {
  abbr: string;
  bar: { name: string; url: string };
  courts: { name: string; url: string };
  // Civil statute of limitations for personal injury (years)
  injurySolYears: number;
  // Top counties by population — used to add geographic specificity
  largestCounties: string[];
  // Common practice areas in this state
  notableLegalContext: string;
}

export const STATE_DATA: Record<string, StateLegalData> = {
  alabama: {
    abbr: "AL",
    bar: { name: "Alabama State Bar", url: "https://www.alabar.org" },
    courts: { name: "Alabama Judicial System", url: "https://judicial.alabama.gov" },
    injurySolYears: 2,
    largestCounties: ["Jefferson", "Mobile", "Madison", "Montgomery", "Shelby"],
    notableLegalContext: "Alabama follows contributory negligence — even 1% fault by the plaintiff can bar recovery, making early case evaluation critical.",
  },
  alaska: {
    abbr: "AK",
    bar: { name: "Alaska Bar Association", url: "https://alaskabar.org" },
    courts: { name: "Alaska Court System", url: "https://courts.alaska.gov" },
    injurySolYears: 2,
    largestCounties: ["Anchorage", "Matanuska-Susitna", "Fairbanks North Star", "Kenai Peninsula", "Juneau"],
    notableLegalContext: "Alaska recognizes pure comparative negligence, allowing recovery even when the plaintiff is 99% at fault.",
  },
  arizona: {
    abbr: "AZ",
    bar: { name: "State Bar of Arizona", url: "https://www.azbar.org" },
    courts: { name: "Arizona Judicial Branch", url: "https://www.azcourts.gov" },
    injurySolYears: 2,
    largestCounties: ["Maricopa", "Pima", "Pinal", "Yavapai", "Mohave"],
    notableLegalContext: "Arizona is a community property state — assets acquired during marriage are typically divided equally in divorce.",
  },
  arkansas: {
    abbr: "AR",
    bar: { name: "Arkansas Bar Association", url: "https://www.arkbar.com" },
    courts: { name: "Arkansas Judiciary", url: "https://www.arcourts.gov" },
    injurySolYears: 3,
    largestCounties: ["Pulaski", "Benton", "Washington", "Sebastian", "Faulkner"],
    notableLegalContext: "Arkansas applies modified comparative negligence with a 50% bar rule.",
  },
  california: {
    abbr: "CA",
    bar: { name: "State Bar of California", url: "https://www.calbar.ca.gov" },
    courts: { name: "California Courts", url: "https://www.courts.ca.gov" },
    injurySolYears: 2,
    largestCounties: ["Los Angeles", "San Diego", "Orange", "Riverside", "San Bernardino"],
    notableLegalContext: "California uses pure comparative negligence and is a community property state. CCP §425.16 (anti-SLAPP) applies broadly.",
  },
  colorado: {
    abbr: "CO",
    bar: { name: "Colorado Bar Association", url: "https://cobar.org" },
    courts: { name: "Colorado Judicial Branch", url: "https://www.courts.state.co.us" },
    injurySolYears: 2,
    largestCounties: ["Denver", "El Paso", "Arapahoe", "Jefferson", "Adams"],
    notableLegalContext: "Colorado caps non-economic damages in personal injury cases and uses modified comparative negligence (50% bar).",
  },
  connecticut: {
    abbr: "CT",
    bar: { name: "Connecticut Bar Association", url: "https://www.ctbar.org" },
    courts: { name: "Connecticut Judicial Branch", url: "https://www.jud.ct.gov" },
    injurySolYears: 2,
    largestCounties: ["Fairfield", "Hartford", "New Haven", "New London", "Litchfield"],
    notableLegalContext: "Connecticut follows modified comparative negligence with a 51% bar rule.",
  },
  delaware: {
    abbr: "DE",
    bar: { name: "Delaware State Bar Association", url: "https://www.dsba.org" },
    courts: { name: "Delaware State Courts", url: "https://courts.delaware.gov" },
    injurySolYears: 2,
    largestCounties: ["New Castle", "Sussex", "Kent"],
    notableLegalContext: "Delaware's Court of Chancery is the nation's leading forum for corporate disputes; over 60% of Fortune 500 companies are incorporated here.",
  },
  florida: {
    abbr: "FL",
    bar: { name: "The Florida Bar", url: "https://www.floridabar.org" },
    courts: { name: "Florida State Courts", url: "https://www.flcourts.gov" },
    injurySolYears: 2,
    largestCounties: ["Miami-Dade", "Broward", "Palm Beach", "Hillsborough", "Orange"],
    notableLegalContext: "Florida adopted modified comparative negligence (50% bar) in 2023, replacing pure comparative negligence.",
  },
  georgia: {
    abbr: "GA",
    bar: { name: "State Bar of Georgia", url: "https://www.gabar.org" },
    courts: { name: "Georgia Courts", url: "https://georgiacourts.gov" },
    injurySolYears: 2,
    largestCounties: ["Fulton", "Gwinnett", "Cobb", "DeKalb", "Chatham"],
    notableLegalContext: "Georgia uses modified comparative negligence with a 50% bar rule and recognizes loss of consortium claims.",
  },
  hawaii: {
    abbr: "HI",
    bar: { name: "Hawaii State Bar Association", url: "https://hsba.org" },
    courts: { name: "Hawaii State Judiciary", url: "https://www.courts.state.hi.us" },
    injurySolYears: 2,
    largestCounties: ["Honolulu", "Hawaii", "Maui", "Kauai"],
    notableLegalContext: "Hawaii is a no-fault auto insurance state with mandatory PIP coverage.",
  },
  idaho: {
    abbr: "ID",
    bar: { name: "Idaho State Bar", url: "https://isb.idaho.gov" },
    courts: { name: "Idaho Courts", url: "https://isc.idaho.gov" },
    injurySolYears: 2,
    largestCounties: ["Ada", "Canyon", "Kootenai", "Bonneville", "Bannock"],
    notableLegalContext: "Idaho is a community property state and uses modified comparative negligence (50% bar).",
  },
  illinois: {
    abbr: "IL",
    bar: { name: "Illinois State Bar Association", url: "https://www.isba.org" },
    courts: { name: "Illinois Courts", url: "https://www.illinoiscourts.gov" },
    injurySolYears: 2,
    largestCounties: ["Cook", "DuPage", "Lake", "Will", "Kane"],
    notableLegalContext: "Illinois follows modified comparative negligence (51% bar) and has a Biometric Information Privacy Act (BIPA) creating significant class-action exposure.",
  },
  indiana: {
    abbr: "IN",
    bar: { name: "Indiana State Bar Association", url: "https://www.inbar.org" },
    courts: { name: "Indiana Courts", url: "https://www.in.gov/courts" },
    injurySolYears: 2,
    largestCounties: ["Marion", "Lake", "Allen", "Hamilton", "St. Joseph"],
    notableLegalContext: "Indiana uses modified comparative fault with a 51% bar.",
  },
  iowa: {
    abbr: "IA",
    bar: { name: "The Iowa State Bar Association", url: "https://www.iowabar.org" },
    courts: { name: "Iowa Judicial Branch", url: "https://www.iowacourts.gov" },
    injurySolYears: 2,
    largestCounties: ["Polk", "Linn", "Scott", "Johnson", "Black Hawk"],
    notableLegalContext: "Iowa applies modified comparative fault (51% bar).",
  },
  kansas: {
    abbr: "KS",
    bar: { name: "Kansas Bar Association", url: "https://www.ksbar.org" },
    courts: { name: "Kansas Judicial Branch", url: "https://www.kscourts.org" },
    injurySolYears: 2,
    largestCounties: ["Johnson", "Sedgwick", "Shawnee", "Wyandotte", "Douglas"],
    notableLegalContext: "Kansas uses modified comparative fault (50% bar).",
  },
  kentucky: {
    abbr: "KY",
    bar: { name: "Kentucky Bar Association", url: "https://www.kybar.org" },
    courts: { name: "Kentucky Court of Justice", url: "https://kycourts.gov" },
    injurySolYears: 1,
    largestCounties: ["Jefferson", "Fayette", "Kenton", "Boone", "Warren"],
    notableLegalContext: "Kentucky has one of the shortest personal-injury statutes of limitation in the country at one year.",
  },
  louisiana: {
    abbr: "LA",
    bar: { name: "Louisiana State Bar Association", url: "https://www.lsba.org" },
    courts: { name: "Louisiana Supreme Court", url: "https://www.lasc.org" },
    injurySolYears: 1,
    largestCounties: ["East Baton Rouge", "Jefferson", "Orleans", "Caddo", "St. Tammany"],
    notableLegalContext: "Louisiana is the only U.S. state using a Civil Code legal system rooted in French and Spanish law, not common law.",
  },
  maine: {
    abbr: "ME",
    bar: { name: "Maine State Bar Association", url: "https://www.mainebar.org" },
    courts: { name: "Maine Judicial Branch", url: "https://www.courts.maine.gov" },
    injurySolYears: 6,
    largestCounties: ["Cumberland", "York", "Penobscot", "Kennebec", "Androscoggin"],
    notableLegalContext: "Maine has one of the longest personal-injury statutes of limitation at six years.",
  },
  maryland: {
    abbr: "MD",
    bar: { name: "Maryland State Bar Association", url: "https://www.msba.org" },
    courts: { name: "Maryland Courts", url: "https://www.mdcourts.gov" },
    injurySolYears: 3,
    largestCounties: ["Montgomery", "Prince George's", "Baltimore", "Anne Arundel", "Howard"],
    notableLegalContext: "Maryland is one of the few jurisdictions still applying contributory negligence in personal-injury cases.",
  },
  massachusetts: {
    abbr: "MA",
    bar: { name: "Massachusetts Bar Association", url: "https://www.massbar.org" },
    courts: { name: "Massachusetts Court System", url: "https://www.mass.gov/courts" },
    injurySolYears: 3,
    largestCounties: ["Middlesex", "Worcester", "Suffolk", "Essex", "Norfolk"],
    notableLegalContext: "Massachusetts uses modified comparative negligence (51% bar) and is a no-fault auto insurance state.",
  },
  michigan: {
    abbr: "MI",
    bar: { name: "State Bar of Michigan", url: "https://www.michbar.org" },
    courts: { name: "Michigan Courts", url: "https://www.courts.michigan.gov" },
    injurySolYears: 3,
    largestCounties: ["Wayne", "Oakland", "Macomb", "Kent", "Genesee"],
    notableLegalContext: "Michigan operates a unique no-fault auto insurance system with significant 2019 reforms reshaping coverage tiers.",
  },
  minnesota: {
    abbr: "MN",
    bar: { name: "Minnesota State Bar Association", url: "https://www.mnbar.org" },
    courts: { name: "Minnesota Judicial Branch", url: "https://www.mncourts.gov" },
    injurySolYears: 6,
    largestCounties: ["Hennepin", "Ramsey", "Dakota", "Anoka", "Washington"],
    notableLegalContext: "Minnesota's six-year personal-injury statute of limitation is among the longest in the nation.",
  },
  mississippi: {
    abbr: "MS",
    bar: { name: "The Mississippi Bar", url: "https://www.msbar.org" },
    courts: { name: "Mississippi Judiciary", url: "https://courts.ms.gov" },
    injurySolYears: 3,
    largestCounties: ["Hinds", "Harrison", "DeSoto", "Rankin", "Madison"],
    notableLegalContext: "Mississippi uses pure comparative negligence — recovery is allowed even at 99% fault.",
  },
  missouri: {
    abbr: "MO",
    bar: { name: "The Missouri Bar", url: "https://mobar.org" },
    courts: { name: "Missouri Courts", url: "https://www.courts.mo.gov" },
    injurySolYears: 5,
    largestCounties: ["St. Louis", "Jackson", "St. Charles", "Greene", "Clay"],
    notableLegalContext: "Missouri has a five-year personal-injury statute of limitation and uses pure comparative negligence.",
  },
  montana: {
    abbr: "MT",
    bar: { name: "State Bar of Montana", url: "https://www.montanabar.org" },
    courts: { name: "Montana Judicial Branch", url: "https://courts.mt.gov" },
    injurySolYears: 3,
    largestCounties: ["Yellowstone", "Missoula", "Gallatin", "Flathead", "Cascade"],
    notableLegalContext: "Montana applies modified comparative negligence (51% bar).",
  },
  nebraska: {
    abbr: "NE",
    bar: { name: "Nebraska State Bar Association", url: "https://www.nebar.com" },
    courts: { name: "Nebraska Judicial Branch", url: "https://supremecourt.nebraska.gov" },
    injurySolYears: 4,
    largestCounties: ["Douglas", "Lancaster", "Sarpy", "Hall", "Buffalo"],
    notableLegalContext: "Nebraska uses modified comparative negligence (50% bar).",
  },
  nevada: {
    abbr: "NV",
    bar: { name: "State Bar of Nevada", url: "https://www.nvbar.org" },
    courts: { name: "Nevada Judicial Branch", url: "https://nvcourts.gov" },
    injurySolYears: 2,
    largestCounties: ["Clark", "Washoe", "Carson City", "Lyon", "Elko"],
    notableLegalContext: "Nevada is a community property state and a popular forum for asset-protection trusts.",
  },
  "new-hampshire": {
    abbr: "NH",
    bar: { name: "New Hampshire Bar Association", url: "https://www.nhbar.org" },
    courts: { name: "New Hampshire Judicial Branch", url: "https://www.courts.nh.gov" },
    injurySolYears: 3,
    largestCounties: ["Hillsborough", "Rockingham", "Merrimack", "Strafford", "Grafton"],
    notableLegalContext: "New Hampshire applies modified comparative negligence (51% bar).",
  },
  "new-jersey": {
    abbr: "NJ",
    bar: { name: "New Jersey State Bar Association", url: "https://njsba.com" },
    courts: { name: "New Jersey Courts", url: "https://www.njcourts.gov" },
    injurySolYears: 2,
    largestCounties: ["Bergen", "Middlesex", "Essex", "Hudson", "Monmouth"],
    notableLegalContext: "New Jersey uses modified comparative negligence (51% bar) and is a verbal-threshold no-fault auto state.",
  },
  "new-mexico": {
    abbr: "NM",
    bar: { name: "State Bar of New Mexico", url: "https://www.sbnm.org" },
    courts: { name: "New Mexico Courts", url: "https://www.nmcourts.gov" },
    injurySolYears: 3,
    largestCounties: ["Bernalillo", "Doña Ana", "Santa Fe", "Sandoval", "San Juan"],
    notableLegalContext: "New Mexico is a community property state using pure comparative negligence.",
  },
  "new-york": {
    abbr: "NY",
    bar: { name: "New York State Bar Association", url: "https://nysba.org" },
    courts: { name: "New York State Unified Court System", url: "https://www.nycourts.gov" },
    injurySolYears: 3,
    largestCounties: ["Kings", "Queens", "New York", "Suffolk", "Bronx"],
    notableLegalContext: "New York uses pure comparative negligence and the Commercial Division handles complex business litigation in major counties.",
  },
  "north-carolina": {
    abbr: "NC",
    bar: { name: "North Carolina Bar Association", url: "https://www.ncbar.org" },
    courts: { name: "North Carolina Judicial Branch", url: "https://www.nccourts.gov" },
    injurySolYears: 3,
    largestCounties: ["Mecklenburg", "Wake", "Guilford", "Forsyth", "Cumberland"],
    notableLegalContext: "North Carolina is one of only four states still applying pure contributory negligence in personal-injury cases.",
  },
  "north-dakota": {
    abbr: "ND",
    bar: { name: "State Bar Association of North Dakota", url: "https://www.sband.org" },
    courts: { name: "North Dakota Courts", url: "https://www.ndcourts.gov" },
    injurySolYears: 6,
    largestCounties: ["Cass", "Burleigh", "Grand Forks", "Ward", "Stark"],
    notableLegalContext: "North Dakota has a six-year personal-injury statute of limitation and uses modified comparative fault.",
  },
  ohio: {
    abbr: "OH",
    bar: { name: "Ohio State Bar Association", url: "https://www.ohiobar.org" },
    courts: { name: "Supreme Court of Ohio", url: "https://www.supremecourt.ohio.gov" },
    injurySolYears: 2,
    largestCounties: ["Franklin", "Cuyahoga", "Hamilton", "Summit", "Montgomery"],
    notableLegalContext: "Ohio applies modified comparative negligence (51% bar) with damages caps on non-economic injuries.",
  },
  oklahoma: {
    abbr: "OK",
    bar: { name: "Oklahoma Bar Association", url: "https://www.okbar.org" },
    courts: { name: "Oklahoma State Courts Network", url: "https://www.oscn.net" },
    injurySolYears: 2,
    largestCounties: ["Oklahoma", "Tulsa", "Cleveland", "Canadian", "Comanche"],
    notableLegalContext: "Oklahoma uses modified comparative negligence (51% bar).",
  },
  oregon: {
    abbr: "OR",
    bar: { name: "Oregon State Bar", url: "https://www.osbar.org" },
    courts: { name: "Oregon Judicial Department", url: "https://www.courts.oregon.gov" },
    injurySolYears: 2,
    largestCounties: ["Multnomah", "Washington", "Clackamas", "Lane", "Marion"],
    notableLegalContext: "Oregon applies modified comparative negligence (51% bar) and caps non-economic damages in some cases.",
  },
  pennsylvania: {
    abbr: "PA",
    bar: { name: "Pennsylvania Bar Association", url: "https://www.pabar.org" },
    courts: { name: "Unified Judicial System of Pennsylvania", url: "https://www.pacourts.us" },
    injurySolYears: 2,
    largestCounties: ["Philadelphia", "Allegheny", "Montgomery", "Bucks", "Delaware"],
    notableLegalContext: "Pennsylvania uses modified comparative negligence (51% bar) and Philadelphia's Court of Common Pleas Complex Litigation Center is known for mass torts.",
  },
  "rhode-island": {
    abbr: "RI",
    bar: { name: "Rhode Island Bar Association", url: "https://www.ribar.com" },
    courts: { name: "Rhode Island Judiciary", url: "https://www.courts.ri.gov" },
    injurySolYears: 3,
    largestCounties: ["Providence", "Kent", "Washington", "Newport", "Bristol"],
    notableLegalContext: "Rhode Island uses pure comparative negligence.",
  },
  "south-carolina": {
    abbr: "SC",
    bar: { name: "South Carolina Bar", url: "https://www.scbar.org" },
    courts: { name: "South Carolina Judicial Branch", url: "https://www.sccourts.org" },
    injurySolYears: 3,
    largestCounties: ["Greenville", "Richland", "Charleston", "Horry", "Spartanburg"],
    notableLegalContext: "South Carolina uses modified comparative negligence (51% bar).",
  },
  "south-dakota": {
    abbr: "SD",
    bar: { name: "State Bar of South Dakota", url: "https://www.statebarofsouthdakota.com" },
    courts: { name: "South Dakota Unified Judicial System", url: "https://ujs.sd.gov" },
    injurySolYears: 3,
    largestCounties: ["Minnehaha", "Pennington", "Lincoln", "Brown", "Brookings"],
    notableLegalContext: "South Dakota applies a unique \"slight vs. gross\" comparative negligence standard.",
  },
  tennessee: {
    abbr: "TN",
    bar: { name: "Tennessee Bar Association", url: "https://www.tba.org" },
    courts: { name: "Tennessee State Courts", url: "https://www.tncourts.gov" },
    injurySolYears: 1,
    largestCounties: ["Shelby", "Davidson", "Knox", "Hamilton", "Rutherford"],
    notableLegalContext: "Tennessee has a one-year personal-injury statute of limitation, among the shortest in the country.",
  },
  texas: {
    abbr: "TX",
    bar: { name: "State Bar of Texas", url: "https://www.texasbar.com" },
    courts: { name: "Texas Judicial Branch", url: "https://www.txcourts.gov" },
    injurySolYears: 2,
    largestCounties: ["Harris", "Dallas", "Tarrant", "Bexar", "Travis"],
    notableLegalContext: "Texas is a community property state that caps medical-malpractice non-economic damages and uses modified comparative fault (51% bar).",
  },
  utah: {
    abbr: "UT",
    bar: { name: "Utah State Bar", url: "https://www.utahbar.org" },
    courts: { name: "Utah State Courts", url: "https://www.utcourts.gov" },
    injurySolYears: 4,
    largestCounties: ["Salt Lake", "Utah", "Davis", "Weber", "Washington"],
    notableLegalContext: "Utah is a no-fault auto insurance state with a four-year personal-injury statute of limitation.",
  },
  vermont: {
    abbr: "VT",
    bar: { name: "Vermont Bar Association", url: "https://www.vtbar.org" },
    courts: { name: "Vermont Judiciary", url: "https://www.vermontjudiciary.org" },
    injurySolYears: 3,
    largestCounties: ["Chittenden", "Rutland", "Washington", "Windsor", "Franklin"],
    notableLegalContext: "Vermont uses modified comparative negligence (51% bar).",
  },
  virginia: {
    abbr: "VA",
    bar: { name: "Virginia State Bar", url: "https://www.vsb.org" },
    courts: { name: "Virginia's Judicial System", url: "https://www.vacourts.gov" },
    injurySolYears: 2,
    largestCounties: ["Fairfax", "Prince William", "Loudoun", "Chesterfield", "Henrico"],
    notableLegalContext: "Virginia is one of the few states still applying pure contributory negligence in personal-injury cases.",
  },
  washington: {
    abbr: "WA",
    bar: { name: "Washington State Bar Association", url: "https://www.wsba.org" },
    courts: { name: "Washington Courts", url: "https://www.courts.wa.gov" },
    injurySolYears: 3,
    largestCounties: ["King", "Pierce", "Snohomish", "Spokane", "Clark"],
    notableLegalContext: "Washington is a community property state using pure comparative negligence.",
  },
  "west-virginia": {
    abbr: "WV",
    bar: { name: "The West Virginia State Bar", url: "https://www.wvbar.org" },
    courts: { name: "West Virginia Judiciary", url: "https://www.courtswv.gov" },
    injurySolYears: 2,
    largestCounties: ["Kanawha", "Berkeley", "Cabell", "Wood", "Monongalia"],
    notableLegalContext: "West Virginia uses modified comparative negligence (51% bar).",
  },
  wisconsin: {
    abbr: "WI",
    bar: { name: "State Bar of Wisconsin", url: "https://www.wisbar.org" },
    courts: { name: "Wisconsin Court System", url: "https://www.wicourts.gov" },
    injurySolYears: 3,
    largestCounties: ["Milwaukee", "Dane", "Waukesha", "Brown", "Racine"],
    notableLegalContext: "Wisconsin applies modified comparative negligence (51% bar) and recognizes parental liability for minors' torts.",
  },
  wyoming: {
    abbr: "WY",
    bar: { name: "Wyoming State Bar", url: "https://www.wyomingbar.org" },
    courts: { name: "Wyoming Judicial Branch", url: "https://www.courts.state.wy.us" },
    injurySolYears: 4,
    largestCounties: ["Laramie", "Natrona", "Campbell", "Sweetwater", "Fremont"],
    notableLegalContext: "Wyoming uses modified comparative fault (51% bar) and recognizes a four-year personal-injury statute of limitation.",
  },
};

export function getStateData(stateSlug: string): StateLegalData | undefined {
  return STATE_DATA[stateSlug];
}
