const fs = require('fs');
const path = require('path');

const VAULT_PATH = path.join(__dirname, '..', 'vault', 'AI Tools');

function slugify(str) {
  return str.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

const tools = [
  { name: "Clio AI", category: "Practice Management", pricing: "Paid", website: "https://www.clio.com", tags: ["practice-management", "legal-ai"], use_cases: ["Case management automation", "Client intake optimization", "Billing and invoicing"], rating: 4.7, featured: true, description: "AI-powered practice management platform for modern law firms.", content: "Clio AI integrates artificial intelligence into its industry-leading practice management platform, helping law firms automate routine tasks.\n\n## Features\n- AI-assisted case management\n- Smart client intake forms\n- Automated billing and time tracking\n- Document management with AI tagging" },
  { name: "Clearbrief AI", category: "Legal Writing", pricing: "Paid", website: "https://www.clearbrief.com", tags: ["legal-writing", "brief-analysis"], use_cases: ["Brief writing assistance", "Fact-checking legal citations", "Writing improvement"], rating: 4.5, featured: false, description: "AI writing assistant that helps lawyers write better briefs with automated fact-checking.", content: "Clearbrief AI analyzes legal briefs and writing to identify unsupported statements and verify citations.\n\n## Features\n- Automatic citation verification\n- Record-based fact checking\n- Writing clarity suggestions\n- Integration with Microsoft Word" },
  { name: "Loio", category: "Contract Analysis", pricing: "Freemium", website: "https://loio.com", tags: ["contract-analysis", "document-review"], use_cases: ["Contract review automation", "Clause comparison", "Risk identification"], rating: 4.3, featured: false, description: "AI-powered contract review tool that identifies risks and compares clauses.", content: "Loio leverages machine learning to review contracts faster and identify potential risks.\n\n## Features\n- AI clause comparison\n- Risk scoring for contract terms\n- Batch document processing\n- Microsoft Word integration" },
  { name: "Legartis", category: "Contract Analysis", pricing: "Paid", website: "https://www.legartis.ai", tags: ["contract-analysis", "risk-assessment"], use_cases: ["Contract risk assessment", "Compliance checking", "Clause extraction"], rating: 4.4, featured: false, description: "Swiss AI platform for automated contract review and risk assessment.", content: "Legartis uses NLP to automatically review contracts and identify risks.\n\n## Features\n- Automated risk identification\n- Multi-language contract analysis\n- Custom risk criteria\n- Regulatory compliance checks" },
  { name: "Smokeball AI", category: "Practice Management", pricing: "Paid", website: "https://www.smokeball.com", tags: ["practice-management", "automation"], use_cases: ["Legal document automation", "Case management", "Time tracking"], rating: 4.5, featured: false, description: "Cloud-based legal practice management with built-in AI document automation.", content: "Smokeball automates legal document creation and practice management tasks.\n\n## Features\n- Automatic time tracking\n- AI document assembly\n- Legal form libraries\n- Cloud-based case files" },
  { name: "Neota Logic", category: "Legal Automation", pricing: "Paid", website: "https://www.neotalogic.com", tags: ["automation", "no-code"], use_cases: ["Legal process automation", "Client self-service portals", "Compliance workflows"], rating: 4.2, featured: false, description: "No-code platform for building legal AI applications and automated workflows.", content: "Neota Logic enables legal teams to build intelligent applications without coding.\n\n## Features\n- No-code application builder\n- Decision tree automation\n- Document assembly\n- Compliance workflow automation" },
  { name: "Tessian", category: "Security", pricing: "Paid", website: "https://www.tessian.com", tags: ["email-security", "compliance"], use_cases: ["Email security for law firms", "Data loss prevention", "Phishing protection"], rating: 4.4, featured: false, description: "AI-powered email security protecting law firms from data breaches.", content: "Tessian uses machine learning to protect law firms from email-based security threats.\n\n## Features\n- AI-powered phishing detection\n- Accidental data loss prevention\n- Client confidentiality protection\n- Real-time threat alerts" },
  { name: "Checkbox AI", category: "Legal Automation", pricing: "Paid", website: "https://www.checkbox.ai", tags: ["automation", "workflow"], use_cases: ["Legal workflow automation", "Contract lifecycle management", "Intake automation"], rating: 4.3, featured: false, description: "No-code legal automation platform for building workflows and client-facing applications.", content: "Checkbox AI enables legal teams to automate repetitive processes without code.\n\n## Features\n- Drag-and-drop workflow builder\n- Client intake automation\n- Contract lifecycle management\n- API integrations" },
  { name: "Darrow AI", category: "Litigation", pricing: "Paid", website: "https://www.darrow.ai", tags: ["litigation", "case-discovery"], use_cases: ["Class action case discovery", "Claim analysis", "Plaintiff identification"], rating: 4.5, featured: false, description: "AI platform that identifies viable legal claims and connects them with attorneys.", content: "Darrow uses AI to scan data and identify potential mass tort and class action cases.\n\n## Features\n- AI-powered case discovery\n- Claim viability assessment\n- Plaintiff matching\n- Case trend monitoring" },
  { name: "Amto AI", category: "Legal Research", pricing: "Freemium", website: "https://www.amto.ai", tags: ["legal-research", "ai-assistant"], use_cases: ["Legal question answering", "Statute lookup", "Case law search"], rating: 4.1, featured: false, description: "AI legal research assistant providing instant answers with citations.", content: "Amto AI provides quick cited answers to legal questions.\n\n## Features\n- Natural language legal queries\n- Citation verification\n- Multi-jurisdiction support\n- Research summaries" },
  { name: "Latch", category: "Contract Analysis", pricing: "Paid", website: "https://www.latch.legal", tags: ["contract-review", "negotiation"], use_cases: ["Contract negotiation", "Redline generation", "Risk scoring"], rating: 4.3, featured: false, description: "AI contract negotiation tool that generates redlines automatically.", content: "Latch automates contract negotiation by analyzing contracts and generating suggested redlines.\n\n## Features\n- Automated redline generation\n- Playbook enforcement\n- Risk scoring\n- Microsoft Word integration" },
  { name: "Syntheia", category: "Client Intake", pricing: "Paid", website: "https://www.syntheia.com", tags: ["client-intake", "ai-receptionist"], use_cases: ["AI phone receptionist", "Client screening", "Appointment scheduling"], rating: 4.2, featured: false, description: "AI receptionist for law firms that handles client calls 24/7.", content: "Syntheia provides an AI-powered virtual receptionist for law firms.\n\n## Features\n- 24/7 AI phone answering\n- Client screening questions\n- Appointment scheduling\n- CRM integration" },
  { name: "Paxton AI", category: "Legal Research", pricing: "Freemium", website: "https://www.paxton.ai", tags: ["legal-research", "drafting"], use_cases: ["Legal research", "Document drafting", "Case analysis"], rating: 4.4, featured: false, description: "AI legal assistant for research, drafting, and case analysis.", content: "Paxton AI combines legal research with document drafting capabilities.\n\n## Features\n- Conversational legal research\n- Draft generation with citations\n- Case law analysis\n- Multi-jurisdiction coverage" },
  { name: "Draftwise", category: "Legal Writing", pricing: "Paid", website: "https://www.draftwise.com", tags: ["legal-writing", "drafting"], use_cases: ["Legal document drafting", "Precedent search", "Clause suggestions"], rating: 4.5, featured: false, description: "AI-powered drafting tool leveraging your firm's own work product.", content: "Draftwise uses AI to search across your firm's document history and suggest relevant language.\n\n## Features\n- Firm-specific precedent search\n- AI clause suggestions\n- Document comparison\n- Knowledge management" },
  { name: "EvenUp", category: "Litigation", pricing: "Paid", website: "https://www.evenuplaw.com", tags: ["personal-injury", "demand-letters"], use_cases: ["Demand letter generation", "Medical record analysis", "Case valuation"], rating: 4.6, featured: true, description: "AI platform generating demand letters for personal injury attorneys.", content: "EvenUp uses AI to analyze medical records and generate comprehensive demand letters.\n\n## Features\n- Automated medical record review\n- AI demand letter generation\n- Case value analysis\n- Treatment timeline creation" },
  { name: "Josef", category: "Legal Automation", pricing: "Paid", website: "https://www.josef.io", tags: ["automation", "chatbot"], use_cases: ["Legal chatbot creation", "Client self-service", "Document automation"], rating: 4.2, featured: false, description: "No-code platform for building legal chatbots.", content: "Josef enables law firms to build conversational AI experiences.\n\n## Features\n- Drag-and-drop chatbot builder\n- Document generation\n- Payment collection\n- Analytics dashboard" },
  { name: "Della AI", category: "Due Diligence", pricing: "Paid", website: "https://www.della.ai", tags: ["due-diligence", "document-review"], use_cases: ["Due diligence automation", "Contract data extraction", "M&A document review"], rating: 4.3, featured: false, description: "AI-powered due diligence platform for M&A transactions.", content: "Della AI automates the due diligence process for M&A transactions.\n\n## Features\n- Bulk document analysis\n- Key term extraction\n- Risk flagging\n- Export to spreadsheet" },
  { name: "Alexsei", category: "Legal Research", pricing: "Paid", website: "https://www.alexsei.com", tags: ["legal-research", "memo-generation"], use_cases: ["Legal memo generation", "Research automation", "Case law analysis"], rating: 4.3, featured: false, description: "AI legal research tool delivering research memos on demand.", content: "Alexsei automates legal research by generating research memos with cited case law.\n\n## Features\n- On-demand research memos\n- Cited case law analysis\n- Multi-jurisdiction support\n- Integration with research platforms" },
  { name: "Courtroom5", category: "Self-Help Legal", pricing: "Freemium", website: "https://www.courtroom5.com", tags: ["self-help", "litigation-support"], use_cases: ["Pro se litigation support", "Court procedure guidance", "Legal document preparation"], rating: 4.0, featured: false, description: "AI-powered platform helping self-represented litigants.", content: "Courtroom5 uses AI to guide self-represented people through court procedures.\n\n## Features\n- Step-by-step procedure guides\n- Document template library\n- AI legal research\n- Motion and pleading assistance" },
  { name: "Jurispect", category: "Compliance", pricing: "Paid", website: "https://www.jurispect.com", tags: ["compliance", "regulatory"], use_cases: ["Regulatory compliance monitoring", "Legal change management", "Risk assessment"], rating: 4.2, featured: false, description: "AI regulatory intelligence platform tracking legal changes.", content: "Jurispect monitors regulatory changes across jurisdictions.\n\n## Features\n- Real-time regulatory tracking\n- Impact assessment\n- Compliance gap analysis\n- Automated alerts" },
  { name: "Lawyerly AI", category: "Legal Writing", pricing: "Freemium", website: "https://www.lawyerly.ai", tags: ["legal-writing", "ai-assistant"], use_cases: ["Legal document drafting", "Contract generation", "Letter writing"], rating: 4.0, featured: false, description: "AI writing assistant for legal document creation.", content: "Lawyerly AI helps attorneys draft legal documents using AI.\n\n## Features\n- Template-based document generation\n- AI writing suggestions\n- Legal terminology assistance\n- Multi-format export" },
  { name: "Henchman AI", category: "Legal Writing", pricing: "Paid", website: "https://www.henchman.io", tags: ["legal-writing", "clause-library"], use_cases: ["Clause library management", "Contract drafting", "Knowledge management"], rating: 4.4, featured: false, description: "AI-powered clause library for faster contract drafting.", content: "Henchman AI creates an intelligent clause library from your firm's existing contracts.\n\n## Features\n- Automated clause extraction\n- Smart search across documents\n- Clause comparison\n- Microsoft Word integration" },
  { name: "Robin AI", category: "Contract Analysis", pricing: "Paid", website: "https://www.robinai.com", tags: ["contract-analysis", "negotiation"], use_cases: ["Contract review", "First-draft negotiation", "Clause standardization"], rating: 4.5, featured: false, description: "AI contract assistant that reviews and negotiates agreements.", content: "Robin AI uses large language models to review and negotiate legal agreements.\n\n## Features\n- AI-powered contract review\n- Automated first-pass negotiation\n- Custom playbook enforcement\n- Enterprise integrations" },
  { name: "PatentPal", category: "IP Law", pricing: "Freemium", website: "https://www.patentpal.com", tags: ["patent", "ip-law"], use_cases: ["Patent drafting", "Specification generation", "Claims analysis"], rating: 4.3, featured: false, description: "AI tool automating patent specification and figure drafting.", content: "PatentPal uses generative AI to create patent specifications from claims.\n\n## Features\n- Automated specification drafting\n- Figure generation\n- Claims analysis\n- Export to standard formats" },
  { name: "Wisedocs AI", category: "Document Review", pricing: "Paid", website: "https://www.wisedocs.ai", tags: ["document-review", "medical-records"], use_cases: ["Medical record organization", "Document chronology", "Key document identification"], rating: 4.4, featured: false, description: "AI platform for organizing medical and legal documents.", content: "Wisedocs AI automates the organization and analysis of medical records.\n\n## Features\n- Automated document sorting\n- Chronological organization\n- Duplicate detection\n- OCR and data extraction" },
  { name: "Briefpoint", category: "Litigation", pricing: "Paid", website: "https://www.briefpoint.ai", tags: ["litigation", "discovery"], use_cases: ["Discovery response drafting", "Interrogatory responses", "Request for admission responses"], rating: 4.5, featured: false, description: "AI tool automating discovery response drafting.", content: "Briefpoint uses AI to draft responses to discovery requests.\n\n## Features\n- Automated response drafting\n- Object-by-object analysis\n- Multiple jurisdiction support\n- Microsoft Word export" },
  { name: "LegalOn", category: "Contract Analysis", pricing: "Paid", website: "https://www.legalon.ai", tags: ["contract-review", "ai-assistant"], use_cases: ["Contract review", "Risk identification", "Negotiation support"], rating: 4.6, featured: true, description: "AI-powered contract review providing expert-level analysis.", content: "LegalOn Technologies uses AI trained by experienced attorneys to review contracts.\n\n## Features\n- Expert-trained AI review\n- Issue spotting and risk flagging\n- Suggested language improvements\n- Microsoft Word integration" },
  { name: "Klarity", category: "Contract Analysis", pricing: "Paid", website: "https://www.klarity.com", tags: ["contract-review", "automation"], use_cases: ["Contract review automation", "Data extraction", "Revenue recognition"], rating: 4.3, featured: false, description: "AI contract review platform for legal and finance teams.", content: "Klarity uses NLP to review contracts and extract key terms.\n\n## Features\n- Automated contract review\n- Business term extraction\n- Revenue recognition support\n- Batch processing" },
  { name: "Norm Ai", category: "Compliance", pricing: "Paid", website: "https://www.norm.ai", tags: ["compliance", "regulatory-ai"], use_cases: ["Regulatory compliance automation", "Policy analysis", "Compliance monitoring"], rating: 4.2, featured: false, description: "AI platform translating regulations into enforceable rules.", content: "Norm Ai converts complex regulations into machine-readable rules.\n\n## Features\n- Regulatory rule extraction\n- Automated compliance monitoring\n- Policy gap analysis\n- Audit trail generation" },
  { name: "Detangle AI", category: "Legal Simplification", pricing: "Free", website: "https://www.detangle.ai", tags: ["legal-simplification", "consumer"], use_cases: ["Legal document simplification", "Terms of service analysis", "Contract understanding"], rating: 4.0, featured: false, description: "Free AI tool that simplifies complex legal documents.", content: "Detangle AI helps anyone understand complex legal documents in plain language.\n\n## Features\n- Plain language translation\n- Key terms highlighting\n- Risk identification\n- Free for personal use" },
  { name: "Diligen", category: "Due Diligence", pricing: "Paid", website: "https://www.diligen.com", tags: ["due-diligence", "contract-review"], use_cases: ["M&A due diligence", "Contract data extraction", "Risk review"], rating: 4.3, featured: false, description: "AI-powered due diligence platform for complex transactions.", content: "Diligen uses machine learning to review contracts during due diligence.\n\n## Features\n- AI document review\n- Custom data extraction\n- Summary generation\n- Secure collaboration" },
  { name: "LawDroid", category: "Legal Automation", pricing: "Freemium", website: "https://www.lawdroid.com", tags: ["chatbot", "client-intake"], use_cases: ["Legal chatbot creation", "Client intake", "Document automation"], rating: 4.1, featured: false, description: "AI platform for creating legal chatbots.", content: "LawDroid helps law firms create AI-powered chatbots for client intake.\n\n## Features\n- AI chatbot builder\n- Client intake automation\n- Document generation\n- Website integration" },
  { name: "CaseMark AI", category: "Document Review", pricing: "Paid", website: "https://www.casemark.ai", tags: ["document-review", "summarization"], use_cases: ["Legal document summarization", "Deposition summaries", "Medical record analysis"], rating: 4.4, featured: false, description: "AI platform creating instant summaries of legal documents.", content: "CaseMark AI generates detailed summaries of complex legal documents.\n\n## Features\n- AI document summarization\n- Deposition digest creation\n- Medical chronology generation\n- Batch processing" },
  { name: "Litera AI", category: "Document Management", pricing: "Paid", website: "https://www.litera.com", tags: ["document-management", "drafting"], use_cases: ["Document comparison", "Version control", "Proofreading"], rating: 4.5, featured: false, description: "AI-powered document management and drafting tools for law firms.", content: "Litera provides comprehensive AI-powered document tools for law firms.\n\n## Features\n- AI document comparison\n- Automated proofreading\n- Version management\n- Microsoft Office integration" },
  { name: "Athennian", category: "Corporate Governance", pricing: "Paid", website: "https://www.athennian.com", tags: ["corporate-governance", "entity-management"], use_cases: ["Entity management", "Corporate governance", "Compliance tracking"], rating: 4.2, featured: false, description: "AI-powered entity management and corporate governance platform.", content: "Athennian uses AI to streamline entity management and corporate governance.\n\n## Features\n- AI entity management\n- Org chart visualization\n- Compliance calendar\n- Multi-jurisdiction support" },
  { name: "Onit AI", category: "Legal Operations", pricing: "Paid", website: "https://www.onit.com", tags: ["legal-ops", "workflow"], use_cases: ["Legal operations automation", "Matter management", "E-billing"], rating: 4.3, featured: false, description: "AI-powered legal operations platform for enterprise legal departments.", content: "Onit provides AI-driven legal operations solutions.\n\n## Features\n- AI workflow automation\n- Enterprise matter management\n- E-billing and invoice review\n- Legal hold management" },
  { name: "TrademarkVision", category: "IP Law", pricing: "Paid", website: "https://www.trademarkvision.com", tags: ["trademark", "ip-law"], use_cases: ["Trademark image search", "Brand monitoring", "IP clearance"], rating: 4.2, featured: false, description: "AI-powered visual trademark search platform.", content: "TrademarkVision uses AI image recognition to search trademark databases.\n\n## Features\n- Visual trademark search\n- AI image similarity detection\n- Global database coverage\n- Clearance reports" },
  { name: "Volody", category: "Contract Management", pricing: "Paid", website: "https://www.volody.com", tags: ["contract-management", "clm"], use_cases: ["Contract lifecycle management", "AI contract drafting", "Obligation tracking"], rating: 4.2, featured: false, description: "AI-powered contract lifecycle management platform.", content: "Volody provides end-to-end contract lifecycle management with AI.\n\n## Features\n- AI contract drafting\n- Lifecycle management\n- Obligation tracking\n- Multi-language support" },
  { name: "Gideon AI", category: "Criminal Defense", pricing: "Freemium", website: "https://www.gideon.ai", tags: ["criminal-defense", "public-defense"], use_cases: ["Criminal case analysis", "Sentencing data analysis", "Case strategy"], rating: 4.1, featured: false, description: "AI platform for criminal defense attorneys.", content: "Gideon AI helps criminal defense attorneys analyze cases and sentencing data.\n\n## Features\n- Case pattern analysis\n- Sentencing data visualization\n- Motion template library\n- Public defender workflow tools" },
  { name: "Doctrine AI", category: "Legal Research", pricing: "Paid", website: "https://www.doctrine.fr", tags: ["legal-research", "european-law"], use_cases: ["European legal research", "Case law search", "Legal intelligence"], rating: 4.4, featured: false, description: "AI-powered legal research for European jurisdictions.", content: "Doctrine uses AI to provide intelligent legal research across European jurisdictions.\n\n## Features\n- AI-powered search\n- Case law analytics\n- European coverage\n- Citation mapping" },
  { name: "Permutable AI", category: "Legal Analytics", pricing: "Paid", website: "https://www.permutable.ai", tags: ["analytics", "esg-compliance"], use_cases: ["ESG compliance monitoring", "Supply chain risk assessment", "Regulatory tracking"], rating: 4.1, featured: false, description: "AI analytics for ESG compliance and supply chain risk.", content: "Permutable AI helps legal teams monitor ESG compliance and assess supply chain risks.\n\n## Features\n- ESG data analysis\n- Supply chain risk mapping\n- Regulatory change tracking\n- Custom alerts" },
  { name: "Orbit Legal", category: "Legal Operations", pricing: "Paid", website: "https://www.orbitlegal.com", tags: ["legal-ops", "matter-management"], use_cases: ["Legal matter management", "Spend management", "Vendor management"], rating: 4.2, featured: false, description: "AI-powered legal operations for matter and spend management.", content: "Orbit helps legal departments manage matters and optimize spending.\n\n## Features\n- AI matter management\n- Legal spend analytics\n- Vendor tracking\n- Reporting dashboards" },
  { name: "Scribe Legal AI", category: "Legal Writing", pricing: "Freemium", website: "https://www.scribelegal.ai", tags: ["legal-writing", "transcription"], use_cases: ["Legal transcription", "Meeting notes", "Deposition summaries"], rating: 4.1, featured: false, description: "AI transcription and note-taking for legal proceedings.", content: "Scribe AI Legal provides accurate transcription of legal proceedings.\n\n## Features\n- Real-time transcription\n- Speaker identification\n- Automated summaries\n- Secure cloud storage" },
  { name: "Verbit Legal", category: "Transcription", pricing: "Paid", website: "https://www.verbit.ai", tags: ["transcription", "legal-proceedings"], use_cases: ["Court reporting", "Deposition transcription", "Legal meeting notes"], rating: 4.3, featured: false, description: "AI-powered legal transcription for court reporting.", content: "Verbit combines AI with human editors for highly accurate legal transcriptions.\n\n## Features\n- 99%+ accuracy transcription\n- Real-time captioning\n- Legal terminology recognition\n- Secure delivery" },
  { name: "Caseflood", category: "Client Intake", pricing: "Paid", website: "https://www.caseflood.com", tags: ["client-intake", "lead-generation"], use_cases: ["Legal lead qualification", "Client intake automation", "Case evaluation"], rating: 4.1, featured: false, description: "AI-powered lead qualification for law firms.", content: "Caseflood uses AI to qualify legal leads and automate client intake.\n\n## Features\n- AI lead scoring\n- Automated intake questionnaires\n- Case merit evaluation\n- Conversion analytics" },
  { name: "Lex Machina IP", category: "Legal Analytics", pricing: "Paid", website: "https://lexmachina.com/ip", tags: ["legal-analytics", "ip-law"], use_cases: ["IP litigation analytics", "Patent case outcomes", "Judge analytics for IP"], rating: 4.6, featured: false, description: "Legal analytics focused on intellectual property litigation.", content: "Lex Machina IP provides data-driven insights specifically for IP litigation.\n\n## Features\n- Patent litigation analytics\n- Trademark case data\n- Judge ruling patterns\n- Damages benchmarking" },
];

let created = 0;
for (const tool of tools) {
  const slug = slugify(tool.name);
  const filename = tool.name + '.md';
  const filePath = path.join(VAULT_PATH, filename);

  if (fs.existsSync(filePath)) continue;

  const md = '---\ntype: ai-tool\nname: \"' + tool.name + '\"\nslug: \"' + slug + '\"\ncategory: \"' + tool.category + '\"\npricing: \"' + tool.pricing + '\"\nwebsite: \"' + tool.website + '\"\naffiliate_link: \"\"\nlogo: \"/images/tools/' + slug + '.png\"\ntags:\n' + tool.tags.map(function(t) { return '  - ' + t; }).join('\n') + '\nuse_cases:\n' + tool.use_cases.map(function(u) { return '  - \"' + u + '\"'; }).join('\n') + '\nrating: ' + tool.rating + '\nfeatured: ' + tool.featured + '\ndescription: \"' + tool.description + '\"\ndate_added: \"2026-01-15\"\n---\n\n# ' + tool.name + '\n\n' + tool.content + '\n';

  fs.writeFileSync(filePath, md);
  created++;
}

console.log('Created ' + created + ' new AI tool files.');
console.log('Total AI tools: ' + fs.readdirSync(VAULT_PATH).filter(function(f) { return f.endsWith('.md'); }).length);
