/**
 * Generate additional AI tool markdown files for the vault.
 * Usage: npx ts-node scripts/generate-tools.ts
 */

import fs from 'fs';
import path from 'path';

const VAULT_PATH = path.join(__dirname, '..', 'vault', 'AI Tools');

function slugify(str: string): string {
  return str.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

interface ToolDef {
  name: string;
  category: string;
  pricing: string;
  website: string;
  tags: string[];
  use_cases: string[];
  rating: number;
  featured: boolean;
  description: string;
  content: string;
}

const tools: ToolDef[] = [
  { name: "Clio AI", category: "Practice Management", pricing: "Paid", website: "https://www.clio.com", tags: ["practice-management", "legal-ai"], use_cases: ["Case management automation", "Client intake optimization", "Billing and invoicing"], rating: 4.7, featured: true, description: "AI-powered practice management platform for modern law firms.", content: "Clio AI integrates artificial intelligence into its industry-leading practice management platform, helping law firms automate routine tasks, manage cases more efficiently, and improve client communication.\n\n## Features\n- AI-assisted case management\n- Smart client intake forms\n- Automated billing and time tracking\n- Document management with AI tagging\n- Client portal with AI chatbot\n\n## Best For\n- Small to mid-size law firms looking for comprehensive practice management\n- Solo practitioners seeking to automate administrative tasks" },
  { name: "Clearbrief AI", category: "Legal Writing", pricing: "Paid", website: "https://www.clearbrief.com", tags: ["legal-writing", "brief-analysis"], use_cases: ["Brief writing assistance", "Fact-checking legal citations", "Writing improvement"], rating: 4.5, featured: false, description: "AI writing assistant that helps lawyers write better briefs with automated fact-checking.", content: "Clearbrief AI analyzes legal briefs and writing to identify unsupported statements, suggest improvements, and verify citations against the actual record.\n\n## Features\n- Automatic citation verification\n- Record-based fact checking\n- Writing clarity suggestions\n- Integration with Microsoft Word\n- Timeline generation from case records" },
  { name: "Loio", category: "Contract Analysis", pricing: "Freemium", website: "https://loio.com", tags: ["contract-analysis", "document-review"], use_cases: ["Contract review automation", "Clause comparison", "Risk identification"], rating: 4.3, featured: false, description: "AI-powered contract review tool that identifies risks and compares clauses.", content: "Loio leverages machine learning to review contracts faster, identify potential risks, and ensure consistency across legal documents.\n\n## Features\n- AI clause comparison\n- Risk scoring for contract terms\n- Batch document processing\n- Custom playbook creation\n- Microsoft Word integration" },
  { name: "Legartis", category: "Contract Analysis", pricing: "Paid", website: "https://www.legartis.ai", tags: ["contract-analysis", "risk-assessment"], use_cases: ["Contract risk assessment", "Compliance checking", "Clause extraction"], rating: 4.4, featured: false, description: "Swiss AI platform for automated contract review and risk assessment.", content: "Legartis uses natural language processing to automatically review contracts, identify risks, and extract key clauses for legal teams.\n\n## Features\n- Automated risk identification\n- Multi-language contract analysis\n- Custom risk criteria\n- Integration with contract management systems\n- Regulatory compliance checks" },
  { name: "Smokeball AI", category: "Practice Management", pricing: "Paid", website: "https://www.smokeball.com", tags: ["practice-management", "automation"], use_cases: ["Legal document automation", "Case management", "Time tracking"], rating: 4.5, featured: false, description: "Cloud-based legal practice management with built-in AI document automation.", content: "Smokeball automates legal document creation and practice management tasks using AI, helping small law firms work more efficiently.\n\n## Features\n- Automatic time tracking\n- AI document assembly\n- Legal form libraries\n- Client relationship management\n- Cloud-based case files" },
  { name: "Lex Machina Analytics", category: "Legal Analytics", pricing: "Paid", website: "https://lexmachina.com", tags: ["legal-analytics", "litigation"], use_cases: ["Litigation outcome prediction", "Judge analytics", "Competitive intelligence"], rating: 4.6, featured: true, description: "Legal analytics platform providing data-driven insights for litigation strategy.", content: "Lex Machina, a LexisNexis company, mines litigation data to provide attorneys with actionable insights about judges, opposing counsel, and case outcomes.\n\n## Features\n- Judge analytics and ruling patterns\n- Case outcome predictions\n- Damages analysis\n- Timing and duration estimates\n- Competitive benchmarking" },
  { name: "Neota Logic", category: "Legal Automation", pricing: "Paid", website: "https://www.neotalogic.com", tags: ["automation", "no-code"], use_cases: ["Legal process automation", "Client self-service portals", "Compliance workflows"], rating: 4.2, featured: false, description: "No-code platform for building legal AI applications and automated workflows.", content: "Neota Logic enables legal teams to build intelligent applications without coding, automating complex legal processes and decision-making.\n\n## Features\n- No-code application builder\n- Decision tree automation\n- Document assembly\n- Integration APIs\n- Compliance workflow automation" },
  { name: "Tessian", category: "Security", pricing: "Paid", website: "https://www.tessian.com", tags: ["email-security", "compliance"], use_cases: ["Email security for law firms", "Data loss prevention", "Phishing protection"], rating: 4.4, featured: false, description: "AI-powered email security protecting law firms from data breaches and compliance violations.", content: "Tessian uses machine learning to protect law firms from email-based security threats, preventing accidental data loss and detecting sophisticated phishing attacks.\n\n## Features\n- AI-powered phishing detection\n- Accidental data loss prevention\n- Client confidentiality protection\n- Compliance monitoring\n- Real-time threat alerts" },
  { name: "Checkbox AI", category: "Legal Automation", pricing: "Paid", website: "https://www.checkbox.ai", tags: ["automation", "workflow"], use_cases: ["Legal workflow automation", "Contract lifecycle management", "Intake automation"], rating: 4.3, featured: false, description: "No-code legal automation platform for building workflows and client-facing applications.", content: "Checkbox AI enables legal teams to automate repetitive processes without writing code, from contract management to compliance tracking.\n\n## Features\n- Drag-and-drop workflow builder\n- Client intake automation\n- Contract lifecycle management\n- Data collection and reporting\n- API integrations" },
  { name: "Darrow AI", category: "Litigation", pricing: "Paid", website: "https://www.darrow.ai", tags: ["litigation", "case-discovery"], use_cases: ["Class action case discovery", "Claim analysis", "Plaintiff identification"], rating: 4.5, featured: false, description: "AI platform that identifies viable legal claims and connects them with attorneys.", content: "Darrow uses AI to scan data and identify potential mass tort and class action cases before they become public, connecting meritorious claims with the right attorneys.\n\n## Features\n- AI-powered case discovery\n- Claim viability assessment\n- Plaintiff matching\n- Evidence analysis\n- Case trend monitoring" },
  { name: "Amto AI", category: "Legal Research", pricing: "Freemium", website: "https://www.amto.ai", tags: ["legal-research", "ai-assistant"], use_cases: ["Legal question answering", "Statute lookup", "Case law search"], rating: 4.1, featured: false, description: "AI legal research assistant providing instant answers to legal questions with citations.", content: "Amto AI provides quick, cited answers to legal questions, helping attorneys save time on preliminary research tasks.\n\n## Features\n- Natural language legal queries\n- Citation verification\n- Multi-jurisdiction support\n- Research summaries\n- Case law extraction" },
  { name: "Latch", category: "Contract Analysis", pricing: "Paid", website: "https://www.latch.legal", tags: ["contract-review", "negotiation"], use_cases: ["Contract negotiation", "Redline generation", "Risk scoring"], rating: 4.3, featured: false, description: "AI contract negotiation tool that generates redlines and identifies risks automatically.", content: "Latch automates contract negotiation by analyzing incoming contracts, identifying risks, and generating suggested redlines based on your playbook.\n\n## Features\n- Automated redline generation\n- Playbook enforcement\n- Risk scoring\n- Version comparison\n- Microsoft Word integration" },
  { name: "Syntheia", category: "Client Intake", pricing: "Paid", website: "https://www.syntheia.com", tags: ["client-intake", "ai-receptionist"], use_cases: ["AI phone receptionist", "Client screening", "Appointment scheduling"], rating: 4.2, featured: false, description: "AI receptionist for law firms that handles client calls, screening, and intake 24/7.", content: "Syntheia provides an AI-powered virtual receptionist that answers phone calls, screens potential clients, and schedules consultations for law firms around the clock.\n\n## Features\n- 24/7 AI phone answering\n- Client screening questions\n- Appointment scheduling\n- Call transcription\n- CRM integration" },
  { name: "Paxton AI", category: "Legal Research", pricing: "Freemium", website: "https://www.paxton.ai", tags: ["legal-research", "drafting"], use_cases: ["Legal research", "Document drafting", "Case analysis"], rating: 4.4, featured: false, description: "AI legal assistant for research, drafting, and case analysis with built-in citation checking.", content: "Paxton AI combines legal research with document drafting capabilities, allowing attorneys to research and draft simultaneously with AI assistance.\n\n## Features\n- Conversational legal research\n- Draft generation with citations\n- Case law analysis\n- Statute interpretation\n- Multi-jurisdiction coverage" },
  { name: "Draftwise", category: "Legal Writing", pricing: "Paid", website: "https://www.draftwise.com", tags: ["legal-writing", "drafting"], use_cases: ["Legal document drafting", "Precedent search", "Clause suggestions"], rating: 4.5, featured: false, description: "AI-powered drafting tool that leverages your firm's own work product for smarter suggestions.", content: "Draftwise uses AI to search across your firm's document history and suggest relevant language, clauses, and precedents for current drafting tasks.\n\n## Features\n- Firm-specific precedent search\n- AI clause suggestions\n- Document comparison\n- Knowledge management\n- Secure on-premise deployment option" },
  { name: "EvenUp", category: "Litigation", pricing: "Paid", website: "https://www.evenuplaw.com", tags: ["personal-injury", "demand-letters"], use_cases: ["Demand letter generation", "Medical record analysis", "Case valuation"], rating: 4.6, featured: true, description: "AI platform that generates demand letters for personal injury attorneys from medical records.", content: "EvenUp uses AI to analyze medical records and generate comprehensive demand letters for personal injury cases, saving attorneys hours of work.\n\n## Features\n- Automated medical record review\n- AI demand letter generation\n- Case value analysis\n- ICD code extraction\n- Treatment timeline creation" },
  { name: "Josef", category: "Legal Automation", pricing: "Paid", website: "https://www.josef.io", tags: ["automation", "chatbot"], use_cases: ["Legal chatbot creation", "Client self-service", "Document automation"], rating: 4.2, featured: false, description: "No-code platform for building legal chatbots and automated client experiences.", content: "Josef enables law firms and legal departments to build conversational AI experiences that guide clients through legal processes.\n\n## Features\n- Drag-and-drop chatbot builder\n- Document generation\n- Payment collection\n- Integration with legal software\n- Analytics dashboard" },
  { name: "Della AI", category: "Due Diligence", pricing: "Paid", website: "https://www.della.ai", tags: ["due-diligence", "document-review"], use_cases: ["Due diligence automation", "Contract data extraction", "M&A document review"], rating: 4.3, featured: false, description: "AI-powered due diligence platform for M&A transactions and contract analysis.", content: "Della AI automates the due diligence process by extracting key data points from large document sets during M&A transactions.\n\n## Features\n- Bulk document analysis\n- Key term extraction\n- Risk flagging\n- Custom data fields\n- Export to spreadsheet" },
  { name: "Alexsei", category: "Legal Research", pricing: "Paid", website: "https://www.alexsei.com", tags: ["legal-research", "memo-generation"], use_cases: ["Legal memo generation", "Research automation", "Case law analysis"], rating: 4.3, featured: false, description: "AI legal research tool that delivers research memos on demand in minutes.", content: "Alexsei automates legal research by generating comprehensive research memos with cited case law in response to natural language questions.\n\n## Features\n- On-demand research memos\n- Cited case law analysis\n- Multi-jurisdiction support\n- Continuous updates\n- Integration with research platforms" },
  { name: "Courtroom5", category: "Self-Help Legal", pricing: "Freemium", website: "https://www.courtroom5.com", tags: ["self-help", "litigation-support"], use_cases: ["Pro se litigation support", "Court procedure guidance", "Legal document preparation"], rating: 4.0, featured: false, description: "AI-powered platform helping self-represented litigants navigate the court system.", content: "Courtroom5 uses AI to guide people representing themselves in court through procedures, document preparation, and legal strategy.\n\n## Features\n- Step-by-step court procedure guides\n- Document template library\n- AI legal research\n- Case timeline management\n- Motion and pleading assistance" },
  { name: "Jurispect", category: "Compliance", pricing: "Paid", website: "https://www.jurispect.com", tags: ["compliance", "regulatory"], use_cases: ["Regulatory compliance monitoring", "Legal change management", "Risk assessment"], rating: 4.2, featured: false, description: "AI regulatory intelligence platform tracking legal changes across jurisdictions.", content: "Jurispect monitors regulatory changes across multiple jurisdictions and helps legal teams stay compliant with evolving requirements.\n\n## Features\n- Real-time regulatory tracking\n- Impact assessment\n- Compliance gap analysis\n- Multi-jurisdiction monitoring\n- Automated alerts" },
  { name: "Caseflood", category: "Client Intake", pricing: "Paid", website: "https://www.caseflood.com", tags: ["client-intake", "lead-generation"], use_cases: ["Legal lead qualification", "Client intake automation", "Case evaluation"], rating: 4.1, featured: false, description: "AI-powered lead qualification and client intake platform for law firms.", content: "Caseflood uses AI to qualify legal leads, automate client intake, and help law firms convert more prospects into clients.\n\n## Features\n- AI lead scoring\n- Automated intake questionnaires\n- Case merit evaluation\n- CRM integration\n- Conversion analytics" },
  { name: "Lawyerly AI", category: "Legal Writing", pricing: "Freemium", website: "https://www.lawyerly.ai", tags: ["legal-writing", "ai-assistant"], use_cases: ["Legal document drafting", "Contract generation", "Letter writing"], rating: 4.0, featured: false, description: "AI writing assistant specialized for legal document creation and letter drafting.", content: "Lawyerly AI helps attorneys draft legal documents, contracts, and correspondence using AI trained on legal language patterns.\n\n## Features\n- Template-based document generation\n- AI writing suggestions\n- Legal terminology assistance\n- Multi-format export\n- Collaboration features" },
  { name: "Henchman AI", category: "Legal Writing", pricing: "Paid", website: "https://www.henchman.io", tags: ["legal-writing", "clause-library"], use_cases: ["Clause library management", "Contract drafting", "Knowledge management"], rating: 4.4, featured: false, description: "AI-powered clause library that helps lawyers draft contracts faster using firm knowledge.", content: "Henchman AI creates an intelligent clause library from your firm's existing contracts, making it easy to find and reuse the best language.\n\n## Features\n- Automated clause extraction\n- Smart search across documents\n- Clause comparison\n- Microsoft Word integration\n- Team collaboration" },
  { name: "Permutable AI", category: "Legal Analytics", pricing: "Paid", website: "https://www.permutable.ai", tags: ["analytics", "esg-compliance"], use_cases: ["ESG compliance monitoring", "Supply chain risk assessment", "Regulatory tracking"], rating: 4.1, featured: false, description: "AI analytics platform for ESG compliance and supply chain risk monitoring in legal contexts.", content: "Permutable AI helps legal teams monitor ESG compliance, assess supply chain risks, and track regulatory developments using natural language processing.\n\n## Features\n- ESG data analysis\n- Supply chain risk mapping\n- Regulatory change tracking\n- Sustainability reporting\n- Custom alerts" },
  { name: "Robin AI", category: "Contract Analysis", pricing: "Paid", website: "https://www.robinai.com", tags: ["contract-analysis", "negotiation"], use_cases: ["Contract review", "First-draft negotiation", "Clause standardization"], rating: 4.5, featured: false, description: "AI contract assistant that reviews, negotiates, and improves legal agreements.", content: "Robin AI uses large language models trained on millions of contracts to review, negotiate, and improve legal agreements automatically.\n\n## Features\n- AI-powered contract review\n- Automated first-pass negotiation\n- Custom playbook enforcement\n- Clause library\n- Enterprise integrations" },
  { name: "Orbit", category: "Legal Operations", pricing: "Paid", website: "https://www.orbitlegal.com", tags: ["legal-ops", "matter-management"], use_cases: ["Legal matter management", "Spend management", "Vendor management"], rating: 4.2, featured: false, description: "AI-powered legal operations platform for matter management and legal spend optimization.", content: "Orbit helps legal departments manage matters, optimize spending, and improve operational efficiency using AI-driven insights.\n\n## Features\n- AI matter management\n- Legal spend analytics\n- Vendor performance tracking\n- Budget forecasting\n- Reporting dashboards" },
  { name: "PatentPal", category: "IP Law", pricing: "Freemium", website: "https://www.patentpal.com", tags: ["patent", "ip-law"], use_cases: ["Patent drafting", "Specification generation", "Claims analysis"], rating: 4.3, featured: false, description: "AI tool that automates patent specification and figure drafting from claims.", content: "PatentPal uses generative AI to automatically create patent specifications, figures, and claims summaries from patent claims.\n\n## Features\n- Automated specification drafting\n- Figure generation\n- Claims analysis\n- Multiple technology domains\n- Export to standard formats" },
  { name: "Wisedocs AI", category: "Document Review", pricing: "Paid", website: "https://www.wisedocs.ai", tags: ["document-review", "medical-records"], use_cases: ["Medical record organization", "Document chronology", "Key document identification"], rating: 4.4, featured: false, description: "AI platform for organizing and analyzing medical and legal documents.", content: "Wisedocs AI automates the organization and analysis of medical records and legal documents, saving litigation teams significant time.\n\n## Features\n- Automated document sorting\n- Chronological organization\n- Duplicate detection\n- Key document flagging\n- OCR and data extraction" },
  { name: "Briefpoint", category: "Litigation", pricing: "Paid", website: "https://www.briefpoint.ai", tags: ["litigation", "discovery"], use_cases: ["Discovery response drafting", "Interrogatory responses", "Request for admission responses"], rating: 4.5, featured: false, description: "AI tool that automates discovery response drafting for litigation attorneys.", content: "Briefpoint uses AI to draft responses to discovery requests including interrogatories, requests for production, and requests for admission.\n\n## Features\n- Automated response drafting\n- Object-by-object analysis\n- Custom response templates\n- Multiple jurisdiction support\n- Microsoft Word export" },
  { name: "Gideon AI", category: "Criminal Defense", pricing: "Freemium", website: "https://www.gideon.ai", tags: ["criminal-defense", "public-defense"], use_cases: ["Criminal case analysis", "Sentencing data analysis", "Case strategy"], rating: 4.1, featured: false, description: "AI platform designed for criminal defense attorneys and public defenders.", content: "Gideon AI helps criminal defense attorneys analyze cases, review sentencing data, and develop defense strategies using artificial intelligence.\n\n## Features\n- Case pattern analysis\n- Sentencing data visualization\n- Motion template library\n- Case outcome predictions\n- Public defender workflow tools" },
  { name: "LegalOn", category: "Contract Analysis", pricing: "Paid", website: "https://www.legalon.ai", tags: ["contract-review", "ai-assistant"], use_cases: ["Contract review", "Risk identification", "Negotiation support"], rating: 4.6, featured: true, description: "AI-powered contract review platform providing expert-level analysis in minutes.", content: "LegalOn Technologies uses AI trained by experienced attorneys to review contracts with the thoroughness of a senior associate.\n\n## Features\n- Expert-trained AI review\n- Issue spotting and risk flagging\n- Suggested language improvements\n- Playbook customization\n- Microsoft Word integration" },
  { name: "Klarity", category: "Contract Analysis", pricing: "Paid", website: "https://www.klarity.com", tags: ["contract-review", "automation"], use_cases: ["Contract review automation", "Data extraction", "Revenue recognition"], rating: 4.3, featured: false, description: "AI contract review platform automating document analysis for legal and finance teams.", content: "Klarity uses natural language processing to review contracts and extract key business terms automatically, serving both legal and finance teams.\n\n## Features\n- Automated contract review\n- Business term extraction\n- Revenue recognition support\n- Custom data models\n- Batch processing" },
  { name: "Norm Ai", category: "Compliance", pricing: "Paid", website: "https://www.norm.ai", tags: ["compliance", "regulatory-ai"], use_cases: ["Regulatory compliance automation", "Policy analysis", "Compliance monitoring"], rating: 4.2, featured: false, description: "AI platform that automates regulatory compliance by translating regulations into enforceable rules.", content: "Norm Ai converts complex regulations into machine-readable rules that can be automatically monitored and enforced across organizations.\n\n## Features\n- Regulatory rule extraction\n- Automated compliance monitoring\n- Policy gap analysis\n- Multi-regulation support\n- Audit trail generation" },
  { name: "Detangle AI", category: "Legal Simplification", pricing: "Free", website: "https://www.detangle.ai", tags: ["legal-simplification", "consumer"], use_cases: ["Legal document simplification", "Terms of service analysis", "Contract understanding"], rating: 4.0, featured: false, description: "Free AI tool that simplifies complex legal documents into plain language.", content: "Detangle AI helps anyone understand complex legal documents by translating legal jargon into clear, plain language summaries.\n\n## Features\n- Plain language translation\n- Key terms highlighting\n- Risk identification\n- Summary generation\n- Free for personal use" },
  { name: "Hammad AI", category: "Legal Research", pricing: "Free", website: "https://www.hammad.ai", tags: ["legal-research", "open-source"], use_cases: ["Open-source legal research", "Case law search", "Legal Q&A"], rating: 3.9, featured: false, description: "Open-source AI legal research tool providing free access to case law analysis.", content: "Hammad AI is an open-source legal research tool that uses AI to help lawyers and students search case law and get answers to legal questions.\n\n## Features\n- Free legal research\n- Case law search\n- AI Q&A assistant\n- Open-source codebase\n- Community-driven development" },
  { name: "Diligen", category: "Due Diligence", pricing: "Paid", website: "https://www.diligen.com", tags: ["due-diligence", "contract-review"], use_cases: ["M&A due diligence", "Contract data extraction", "Risk review"], rating: 4.3, featured: false, description: "AI-powered due diligence and contract review platform for complex transactions.", content: "Diligen uses machine learning to review and extract data from contracts during due diligence processes, dramatically reducing review time.\n\n## Features\n- AI document review\n- Custom data extraction\n- Summary generation\n- Multi-document comparison\n- Secure collaboration" },
  { name: "LawDroid", category: "Legal Automation", pricing: "Freemium", website: "https://www.lawdroid.com", tags: ["chatbot", "client-intake"], use_cases: ["Legal chatbot creation", "Client intake", "Document automation"], rating: 4.1, featured: false, description: "AI platform for creating legal chatbots and automating client interactions.", content: "LawDroid helps law firms create AI-powered chatbots for client intake, FAQs, and document preparation without coding.\n\n## Features\n- AI chatbot builder\n- Client intake automation\n- Document generation\n- Appointment scheduling\n- Website integration" },
  { name: "Doctrine AI", category: "Legal Research", pricing: "Paid", website: "https://www.doctrine.fr", tags: ["legal-research", "european-law"], use_cases: ["European legal research", "Case law search", "Legal intelligence"], rating: 4.4, featured: false, description: "AI-powered legal research platform specializing in European and French law.", content: "Doctrine uses AI to provide intelligent legal research across European jurisdictions, with powerful search and analysis capabilities.\n\n## Features\n- AI-powered search\n- Case law analytics\n- European jurisdiction coverage\n- Citation mapping\n- Legal trend analysis" },
  { name: "Volody", category: "Contract Management", pricing: "Paid", website: "https://www.volody.com", tags: ["contract-management", "clm"], use_cases: ["Contract lifecycle management", "AI contract drafting", "Obligation tracking"], rating: 4.2, featured: false, description: "AI-powered contract lifecycle management platform with intelligent drafting and analytics.", content: "Volody provides end-to-end contract lifecycle management with AI-powered drafting, review, and obligation tracking capabilities.\n\n## Features\n- AI contract drafting\n- Lifecycle management\n- Obligation tracking\n- Analytics dashboard\n- Multi-language support" },
  { name: "TrademarkVision", category: "IP Law", pricing: "Paid", website: "https://www.trademarkvision.com", tags: ["trademark", "ip-law"], use_cases: ["Trademark image search", "Brand monitoring", "IP clearance"], rating: 4.2, featured: false, description: "AI-powered visual trademark search and brand monitoring platform.", content: "TrademarkVision uses AI image recognition to search trademark databases visually, helping IP attorneys conduct more thorough clearance searches.\n\n## Features\n- Visual trademark search\n- AI image similarity detection\n- Global trademark database coverage\n- Brand monitoring alerts\n- Clearance reports" },
  { name: "Onit AI", category: "Legal Operations", pricing: "Paid", website: "https://www.onit.com", tags: ["legal-ops", "workflow"], use_cases: ["Legal operations automation", "Matter management", "E-billing"], rating: 4.3, featured: false, description: "AI-powered legal operations platform for enterprise legal departments.", content: "Onit provides AI-driven legal operations solutions including workflow automation, matter management, and e-billing for corporate legal departments.\n\n## Features\n- AI workflow automation\n- Enterprise matter management\n- E-billing and invoice review\n- Contract lifecycle management\n- Legal hold management" },
  { name: "Scribe AI Legal", category: "Legal Writing", pricing: "Freemium", website: "https://www.scribelegal.ai", tags: ["legal-writing", "transcription"], use_cases: ["Legal transcription", "Meeting notes", "Deposition summaries"], rating: 4.1, featured: false, description: "AI transcription and note-taking tool designed for legal proceedings.", content: "Scribe AI Legal provides accurate transcription and intelligent summarization of legal meetings, depositions, and court proceedings.\n\n## Features\n- Real-time transcription\n- Speaker identification\n- Automated summaries\n- Key point extraction\n- Secure cloud storage" },
  { name: "CaseMark AI", category: "Document Review", pricing: "Paid", website: "https://www.casemark.ai", tags: ["document-review", "summarization"], use_cases: ["Legal document summarization", "Deposition summaries", "Medical record analysis"], rating: 4.4, featured: false, description: "AI platform that creates instant summaries of legal documents and depositions.", content: "CaseMark AI generates accurate, detailed summaries of complex legal documents including depositions, medical records, and case files.\n\n## Features\n- AI document summarization\n- Deposition digest creation\n- Medical chronology generation\n- Custom summary templates\n- Batch processing" },
  { name: "Athennian", category: "Corporate Governance", pricing: "Paid", website: "https://www.athennian.com", tags: ["corporate-governance", "entity-management"], use_cases: ["Entity management", "Corporate governance", "Compliance tracking"], rating: 4.2, featured: false, description: "AI-powered entity management and corporate governance platform.", content: "Athennian uses AI to streamline entity management, corporate governance, and compliance for legal teams managing complex corporate structures.\n\n## Features\n- AI entity management\n- Org chart visualization\n- Compliance calendar\n- Document generation\n- Multi-jurisdiction support" },
  { name: "Litera AI", category: "Document Management", pricing: "Paid", website: "https://www.litera.com", tags: ["document-management", "drafting"], use_cases: ["Document comparison", "Version control", "Proofreading"], rating: 4.5, featured: false, description: "AI-powered document management and drafting tools for law firms.", content: "Litera provides a comprehensive suite of AI-powered document tools for law firms, including comparison, proofreading, and version control.\n\n## Features\n- AI document comparison\n- Automated proofreading\n- Version management\n- Template management\n- Microsoft Office integration" },
  { name: "AI Transcription Legal", category: "Transcription", pricing: "Paid", website: "https://www.verbit.ai", tags: ["transcription", "legal-proceedings"], use_cases: ["Court reporting", "Deposition transcription", "Legal meeting notes"], rating: 4.3, featured: false, description: "AI-powered legal transcription service for court reporting and depositions.", content: "Verbit combines AI with human editors to deliver highly accurate legal transcriptions for court proceedings, depositions, and meetings.\n\n## Features\n- 99%+ accuracy transcription\n- Real-time captioning\n- Speaker identification\n- Legal terminology recognition\n- Secure delivery" },
];

let created = 0;
for (const tool of tools) {
  const slug = slugify(tool.name);
  const filename = `${tool.name}.md`;
  const filePath = path.join(VAULT_PATH, filename);

  if (fs.existsSync(filePath)) continue;

  const md = `---
type: ai-tool
name: "${tool.name}"
slug: "${slug}"
category: "${tool.category}"
pricing: "${tool.pricing}"
website: "${tool.website}"
affiliate_link: ""
logo: "/images/tools/${slug}.png"
tags:
${tool.tags.map(t => `  - ${t}`).join('\n')}
use_cases:
${tool.use_cases.map(u => `  - "${u}"`).join('\n')}
rating: ${tool.rating}
featured: ${tool.featured}
description: "${tool.description}"
date_added: "2026-01-15"
---

${tool.content}
`;

  fs.writeFileSync(filePath, md);
  created++;
}

console.log(`Created ${created} new AI tool files.`);
console.log(`Total AI tools: ${fs.readdirSync(VAULT_PATH).filter(f => f.endsWith('.md')).length}`);
